### PR TITLE
HiGHS subtree

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

Adds HiGHS subtree for WIP [#11759](https://github.com/scipy/scipy/pull/11759)

#### What does this implement/fix?

- Uses git [subtree](https://www.atlassian.com/git/tutorials/git-subtree) to embed [HiGHS](https://github.com/ERGO-Code/HiGHS) source code into scipy
- A [fork of HiGHS](https://github.com/mckib2/HiGHS) is used which contains Cython wrappers for interfacing with the C/C++ codebase
- Build is integrated into scipy, using numpy.distutils
- Changes imports in `_linprog_highs.py` to use _highs module
- Build has been verified on Ubuntu 18.04, Python 3.7.7, gcc 7.5.0, will be testing Windows 10 and Mac shortly
- Passes all but 2 unittests (on my machine, that is)

#### Additional information

As discussed in link above, git subtrees can be a simpler model than git submodules for including git repos inside of scipy.  The contents of the subtree are available right after clone of project as opposed to a submodule.   The history of the subtree is also not required to be carried by scipy, can simply be squashed.

Updating is simple(-ish):
```
git subtree pull --prefix=scipy/optimize/_highs https://github.com/mckib2/HiGHS.git master --squash
```

One quirk of subtrees is that "the responsibility of not mixing super and sub-project code in commits lies with you," meaning that commits for upstream changes to HiGHS should be done separately than those intented for other elements of scipy.

Upstream changes can be pushed to upstream master like this (after adding HiGHS as a remote):
```
git subtree push --prefix=scipy/optimize/_highs highs-upstream-remote master
```

### CODE REVIEW

**Comment by mckib2** [comment]
Fixed Windows `/std:c++14` issue

**Comment by mdhaber** [comment]
Works on Windows! And yes, now I see the same two failures you do.

**Comment by mdhaber** [comment]
I didn't have a problem with that on Windows, but I just did on Mac.
I was going to say one thing to fix is that we shouldn't have untracked files after building:
```
(scipydev) C:\Users\matth\Desktop\scipy>git status
On branch embed-highs
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        scipy/optimize/_highs/pyHiGHS/src/highs_wrapper.cxx
        scipy/optimize/_highs/pyHiGHS/src/linprog.cxx
        scipy/optimize/_highs/pyHiGHS/src/linprog_mps.cxx
        scipy/optimize/_highs/pyHiGHS/src/mpswriter.cxx
```

**Comment by mckib2** [comment]
> Works on Windows! And yes, now I see the same two failures you do.

I'll look at the two failure cases tomorrow.  Do you mind making MPS files for them with MATLAB?  It will help to communicate failures to HiGHS team

> I didn't have a problem with that on Windows, but I just did on Mac.

What issues on Mac?  I did get just my HiGHS fork building on mac, so hopefully it's something superficial.

> I was going to say one thing to fix is that we shouldn't have untracked files after building:

It's good practice anyway to commit cython-generated files, I'll take care of that tomorrow as well

**Comment by mdhaber** [comment]
On mac it complained about `std:c++14` something. If it doesn't happen again after this most recent update, it was probably the same thing you said you fixed.

**Comment by mdhaber** [comment]
Hmm still `clang: error: no such file or directory: 'std=c++14'` on mac

**Comment by mckib2** [comment]
Whoops, that's a typo -- should be `-std=c++14`

**Comment by mdhaber** [comment]
> I'll look at the two failure cases tomorrow. Do you mind making MPS files for them with MATLAB?

Yes, but why aren't they failing with pyHiGHS and my PR? Why do they only start failing with this `embed-highs`?

**Comment by mckib2** [comment]
> Whoops, that's a typo -- should be -std=c++14

Just pushed a fix, does that fix Mac error?

> Yes, but why aren't they failing with pyHiGHS and my PR? Why do they only start failing with this embed-highs?

Honestly can't say, those two errors have been the only ones for me for a few days now I think

**Comment by mdhaber** [comment]
It appears to have built on Mac. Testing now; if it works, I'll merge.

**Comment by mdhaber** [comment]
`python setup.py` build works and I can import, but build fails when I try to run the tests.
https://www.dropbox.com/s/eqc3vlfap3oggow/lderror.txt?dl=0

I'll try to generate those MPS files soon but I think that's it for tonight. Nice work!

**Comment by mckib2** [comment]
It looks like build errors due to other modules, but highs_wrapper working as expected? Are you able to build scipy master on macos and run tests?

This is me not knowing anything about mac, but what Python build are you using?  [This guide](https://docs.scipy.org/doc/scipy/reference/building/macosx.html) warns about using Apple's distribution

**Comment by mdhaber** [comment]
I use Anaconda. 
You're right, master is not building or testing. I didn't even think to try because building has been reliable on that machine for so long.
If you're happy with this, shall I merge and see how it fares on CI?

**Comment by mckib2** [comment]
I think passing CI is the next big hurdle (besides last two unittests), so I say let's try it!

**Comment by mdhaber** [comment]
So merge?

**Comment by mckib2** [comment]
Yes

**Pull request merged**
