### PR TITLE
WIP: fixes for M1 speculative execution

### PR DESCRIPTION
**Pull request by mckib2**
- Updates Boost submodule to apply patches from https://github.com/boostorg/math/pull/945 to this SciPy branch

### CODE REVIEW

**Comment by mckib2** [comment]
@mdhaber This resolves all errors on this branch locally on the M1 Mac Mini.  Still waiting to hear back from upstream if they can reproduce the issues/want to accept theses

The evidence seems to suggest that M1 speculative execution is failing to suppress failed branch exceptions in these cases.  So the fixes are to try to dance around what we think the speculative execution is going to run into.  Not sure if these issues are present in the latest firmware/updates for MacOS, so I'm delaying updating the Mac Mini

**Comment by mdhaber** [comment]
Ooh, let me make sure I understand correctly:

> The evidence seems to suggest that M1 speculative execution is failing to suppress failed branch exceptions in these cases.

Does this mean that it is supposed to be suppressing them but doesn't, and that an update to the firmware might fix that?

This suggests to me that the warnings are indeed harmless, if they are meant to be suppressed?

**Comment by mckib2** [comment]
> Does this mean that it is supposed to be suppressing them but doesn't, and that an update to the firmware might fix that?

It could be firmware or just an OS upgrade.  The SciPy job is using a [9 month old image](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-monterey-xcode/22082164?tag=13.3.1), so we might try bumping that to see if it helps

> This suggests to me that the warnings are indeed harmless, if they are meant to be suppressed?

Yes, they are harmless, just annoying.  Failed branches can catastrophically fail and the user _shouldn't_ see any indication

**Comment by mckib2** [comment]
[This line](https://github.com/scipy/scipy/blob/c651eb9cbfb6ff67c864b4e7da6b69d9b293b802/ci/cirrus_wheels.yml#L45) could be changed to point to the latest image -- are you able to run that pipeline from your SciPy fork or this testing that must be done in the main repo?

**Comment by mdhaber** [comment]
Go ahead and test in the main repo. It's worth it.

**Pull request closed without merging**
