### PR TITLE
Upstream 2020 07 07

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

https://github.com/scipy/scipy/pull/12043

#### What does this implement/fix?

- upstream fixes
- A couple more type checks for option warnings
- smoke/sniff tests to make to increase code coverage of `highs_wrapper.pyx`

#### Additional information

The added unit tests are not meant as unit tests in the religious sense -- they are there to walk through the lines of code.  Code coverage and Cython is hard, so this was my attempt at getting coverage of as many branches as I could.  It lead to the inclusion of a couple of more type checks as errors were discovered

### CODE REVIEW

**Comment by mckib2** [comment]
I've added a [python file](https://github.com/mdhaber/scipy/pull/23/files#diff-cc2e173e99737ea94e5d0aa8d867593d), you might want to look it over and make sure it's not going to break anything in scipy flake8-wise.  I don't have the time to do that tonight

**Comment by mckib2** [comment]
The following command now runs clean for me:
```
flake8 scipy/optimize/_highs/pyHiGHS/tests/
```

**Comment by mdhaber** [comment]
OK. Shall I merge now?

**Comment by mckib2** [comment]
Good on my end

**Pull request merged**
