### PR TITLE
Upstream 2020 04 27

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

https://github.com/scipy/scipy/pull/11759

#### What does this implement/fix?

- changes in `_linprog_highs.py` due to https://github.com/scipy/scipy/pull/11759#pullrequestreview-401458451
- lots of upstream changes (https://github.com/ERGO-Code/HiGHS/pull/327)
    - `highs_wrapper.pyx` now checks primal feasibility to know if solution exists https://github.com/ERGO-Code/HiGHS/issues/324
    - `mpswriter.pyx` uses new API
    - `ipm` now runs silently https://github.com/ERGO-Code/HiGHS/issues/323
    - Failing one unit tests `test_enzo_example_c_with_infeasibility` (simplex, no presolve -- upstream issue https://github.com/ERGO-Code/HiGHS/issues/334)
    - Reopened issue for IPX without presolve: https://github.com/ERGO-Code/HiGHS/issues/280

#### Additional information

Ready to merge after upstream changes for newest failing unit test

### CODE REVIEW

**Comment by mdhaber** [comment]
OK you let me know when.

**Comment by mckib2** [comment]
Unit test failure appears to be due to `highs_wrapper`.  I'll try to debug tomorrow.

_EDIT: This is a simplex failure, not IPM like a mistakenly thought and is a bug with HiGHS.  Submitted upstream bug report: https://github.com/ERGO-Code/HiGHS/issues/334_

**Comment by mckib2** [comment]
It didn't make any tests fail, but I did notice that model status enum values changed (one got moved) in this past upstream update.  To combat this variability, I am now exporting the enum values from `highs_wrapper.pyx` and `_linprog_highs.py` now uses those variables instead of hard coding status values.

**Comment by mckib2** [comment]
Can we add a unit test to catch https://github.com/ERGO-Code/HiGHS/issues/280?  We originally identified this bug a month ago and it is failing again currently for IPM with no presolve.  Julian happened to catch it by chance it looks like...

**Comment by mdhaber** [comment]
Is this PR ready to merge?
Sure I can add that test, but it sounds like it would make the test suite fail. That might reduce the chances of completing review before 1.5.0 is released. Do you want to wait to add it until it gets fixed?

**Comment by mckib2** [comment]
The test suite is currently failing HiGHS simplex `test_enzo_example_c_with_infeasibility`.  I think we need this merged to remove stdout output from the IPX solver.

What is the policy on adding expected failures?  There are bugs submitted upstream that are not our fault, so I feel fine marking them as expected failures until we can get upstream fixes (potentially after the 1.5.0 release).

We should also make sure pretty soon that none of the changes in the pull result in platform build errors to give us time to fix those.

My recommendations:
- create new test case for https://github.com/ERGO-Code/HiGHS/issues/280
- mark new test case and HiGHS Simplex `test_enzo_example_c_with_infeasibility` as expected failures
- merge

**Comment by mdhaber** [comment]
> What is the policy on adding expected failures?

We can skip the test; it's not really a matter of policy. The question is really "what is the best thing to do?". That depends on why `test_enzo_example_c_with_infeasibility` is failing. If it's a very pathological problem, I think it's OK to skip the test. But if we can imagine a lot of users trying `highs-simplex` and running into the same underlying issue with their own problems, then merging this and skipping the test might not be the best thing to do. We'd get a lot of bug reports that might be real or might be noise, and the users would get a bad impression of the new solvers. On the other hand, if we don't merge this PR, then IPX would produce console output. That's a lot easier to deal with if we do get bug reports. I suppose we'd also need to assess how that would affect users' impressions of the new methods. Does that make sense?

**Comment by mckib2** [comment]
> Does that make sense?

Yes

>  The question is really "what is the best thing to do?"

I'll defer to your judgement.  I'll keep following up upstream to track progress, let me know what to prioritize for the 1.5.0 release

**Comment by mckib2** [comment]
Here's a test that shows a mismatch in slack values:
```
#######################################
# HiGHS-Simplex Option-Specific Tests #
#######################################


class TestLinprogHiGHSSimplex(LinprogHiGHSTests):
    method = "highs-simplex"
    options = {}

    def test_nontrivial_problem_slack(self):

        c, A_ub, b_ub, A_eq, b_eq, x_star, f_star = nontrivial_problem()
        res0 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, method='revised simplex')
        res1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, method='highs-simplex')
        print(res0.slack, res1.slack)
        assert_allclose(res0.slack, res1.slack, atol=1e-10)
```

Output is:
```
res0.slack: [-1.77635684e-15  6.97843278e+00  1.77635684e-15  4.45291157e+00]
res1.slack: [0.0, 6.9784327821711, 0.0, 4.452911574406901, 0.0]
```

`highs_wrapper` is giving an extra 0 at the end for some reason.

@mdhaber Do you want me to start fixes here?

**Comment by mdhaber** [comment]
> Do you want me to start fixes here? 

What sort of fixes? To the slack? I'm thinking we should just calculate the `slack` and `res` inside `linprog_highs.py` to kill the issue.

> let me know what to prioritize for the 1.5.0 release

I think the most important thing is getting this reviewed. I'm not sure how much there is to be done other than that and responses to the comments in gh-11759, which will not take me long to address when I get a moment. I suppose in the meantime it would help if you could look into 5 and 6:

> 5
> When I changed message_level option, it looks like that nothing changed. What was going to change?
> 6
> When I input an invalid integer for an option, for example "simplex_dual_edge_weight_strategy": -1, nothing happened. Invalid input validation and error message would be better to be added.

**Comment by mckib2** [comment]
> I'm thinking we should just calculate the slack and res inside linprog_highs.py to kill the issue.

That sounds good for now.  I'll try to track down where the issue is in the wrapper so we can get a fix in down the line.

> 5
When I changed message_level option, it looks like that nothing changed. What was going to change?

```
options = {
    ...
    'message_level': message_level*disp,
    ...
}
```

it's being multiplied by `disp` which is `False` by default.  Setting `disp=True` should be enough to see changes to `message_level`.

>6
When I input an invalid integer for an option, for example "simplex_dual_edge_weight_strategy": -1, nothing happened. Invalid input validation and error message would be better to be added.

When run with `message_level=1` the following warning is printed:
```
WARNING: checkOptionValue: Value -1 for option "simplex_dual_edge_weight_strategy" is below lower bound of 0
```

The default is used when an invalid value is found.  I'll look into seeing if it is possible to identify invalid options from HiGHS and pass the warning forward through the wrapper.

**Comment by mckib2** [comment]
I forgot we already had the discussion about `slack`/`con` [here](https://github.com/scipy/scipy/pull/11759#issuecomment-615039643).  This seems to be the fix in `_linprog_highs.py`:
```
    # HiGHS represents constraints as lhs/rhs, so
    # Ax + s = b => Ax = b - s
    # and we need to split up s by A_ub and A_eq
    slack = res.get('slack', None)
    con = None
    if slack is not None:
        con = slack[len(b_ub):]
        slack = slack[:len(b_ub)]

    sol = {'x': res.get('x', None),
           'slack': slack,
           # TODO: Add/test dual info like:
           # 'lambda': res.get('lambda', None),
           # 's': res.get('s', None),
           'fun': res.get('fun', None),
           'con': con,
           'status': statuses[res['status']][0],
           'success': res['status'] == MODEL_STATUS_OPTIMAL,
           'message': statuses[res['status']][1],
           'nit': (res.get('simplex_nit', 0) if solver == 'simplex'
                   else res.get('ipm_nit', 0))
           }
```

**Comment by mckib2** [comment]
Update: bug has been identified that causes `test_enzo_example_c_with_infeasibility` to fail, fix is in the works (see https://github.com/ERGO-Code/HiGHS/issues/334)

**Comment by mckib2** [comment]
@mdhaber It looks ready to merge to me: all unit tests are passing.  I don't get anything on stdout when I run IPX with presolve=on, but I am still getting output with presolve=off.  Can you give it a go and check as well?  I've already got a few issues with them open, I'll wait to a few of those are resolved before bringing this up with the HiGHS team.

Even though there's still some stdout issues, I'd like to get it over there anyway to make sure no CI builds broke...  I'll keep looking at how to suppress those for IPX+presolve.  This PR got a little bigger than I wanted

I also added:
- Documentation for missing message_level ML_ALWAYS
- Added `None` as an option for `solver` in the documentation and made a note that HiGHS will choose the solver if `None` is given
- Added a bunch of "hidden" advanced option support to `highs_wrapper` -- not needed for `_linprog_highs.pyx` (it's documented in `highs_wrapper` docstring)
- slack/con should now be working as expected
- `_replace_inf` now uses `np.isinf`

There is another fix coming on the way from https://github.com/ERGO-Code/HiGHS/pull/341 to make sure invalid iterator dereferencing is avoided.  It only breaks Windows debug builds but luckily we only ever build in release, so we can wait -- not critical for us.

**Comment by mckib2** [comment]
Apologies -- had a few unneeded files sneak back in, removed them.  Ready to merge.

**Pull request merged**
