### PR TITLE
ENH: update PROPACK submodule commit hash

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

https://github.com/scipy/scipy/pull/15214

#### What does this implement/fix?

- updates PROPACK submodule commit to the latest which excludes large example files

### CODE REVIEW

**Comment by mckib2** [comment]
@mdhaber Taking the long way around -- I know there should be a way to push to your branch directly, but checked out your branch headless and short of time this evening to resolve it, so just branched off of you and made this PR

**Comment by mdhaber** [comment]
I don't think this has my changes. They can be merged separately, though.

**Comment by mckib2** [comment]
> I don't think this has my changes. They can be merged separately, though.

Which changes are those then?  This is based on your `resize_propack_tests` branch, so should have all those changes and then this single submodule commit on top of that

**Comment by mdhaber** [comment]
I misunderstood. I thought this was the SciPy repo : ) This is for merging into my branch. Got it.

**Pull request merged**
