### PR TITLE
Update gh13096

### PR DESCRIPTION
**Pull request by andyfaff**
I checked out your `minimize_equal_bounds` branch, then rebased on scipy/master (hence the large number of commits), fixing a few merge conflicts. I then made some changes to get the tests to pass, and added a small extra test with constraints.

This was so we can discuss the issue more clearly on Wednesday.

### CODE REVIEW

**Comment by andyfaff** [comment]
@mdhaber, I reckon this modification is slightly cleaner for the bounds handling. Going to add more tests now.

**Comment by andyfaff** [comment]
These tests pass locally. Please merge to your branch if they look ok to you.

**Comment by mdhaber** [comment]
Yeah, last night i was wondering why I didn't just convert everything to new style bounds and grab from that. So good idea.

**Comment by mdhaber** [comment]
Thanks for this!

I used some ideas from it (e.g. using `standardize_constraints` so we can eliminate `_split_bounds` and simplify `_remove_from_bounds`) but didn't simply merge, mostly because I needed to think through it myself. 

Afterwards, I took a closer look at what you had here and, in the end, I see that I ended up with something very similar. A few differences:
* further simplification of the use of `standardize_bounds` (eliminated one of the calls)
* `x_fixed = ((lb+ub)/2)[i_fixed]` -> `x_fixed = lb[i_fixed]`
* Additional logic for `remove_vars` - as you noted, we don't need to remove variables if analytical gradient and constraint jacobian are provided. I suppose we can always eliminate the variables if we want to simplify this logic at the expense of losing the gradient/jacobian information involving the fixed variables (even when all gradient/jacobian functions are provided).
* Added "TNC" (which also uses gradients), removed "Powell" (which doesn't)

Also, "factorize" doesn't sound to me like a word for "remove fixed variables", so I stuck with "remove fixed variables".

I haven't taken a close look at the test yet; I will soon.

**Pull request merged**
