### PR TITLE
HiGHS

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

HiGHS linprog integration [#11759](https://github.com/scipy/scipy/pull/11759)

#### What does this implement/fix?

- Downgrade to `c++11` standard
- Remove hardcoded compiler optimizations
- various upstream fixes for build warnings

#### Additional information

Not ready to merge yet, still have a few things left on the wishlist:
- ~~dual values~~
- ~~sensitivity analysis values?~~
- documentation

### CODE REVIEW

**Comment by mdhaber** [comment]
> dual values, sensitivity analysis

We can wait on these for another PR. It will make it easier on reviewers, I think, if we limit this to the current `linprog` functionality.

I was trying to run the linprog benchmarks and they all failed with the HiGHS solvers. I don't have time to debug right now (I must have done something silly) but the main issue is getting so long that even if I make a note there I might not notice it. Please try to help me remember not to merge before we get the benchmarks working : )

**Comment by mckib2** [comment]
When you get a chance let me know what failed and I can try to take a look.

> but the main issue is getting so long that even if I make a note there I might not notice it.

This is quite the marathon, thanks for hanging in there with me

**Comment by mdhaber** [comment]
There was nothing wrong. Unless instructed otherwise, `asv` uses the benchmark files of the active branch to benchmark the master branch of a repo, not the active branch. The master branch didn't have the HiGHS methods, so all the benchmarks failed. Once I insisted that it benchmark the active branch, everything was fine.

**Comment by mckib2** [comment]
@mdhaber I got some more info about HiGHS about how to find slack variables and Lagrange multipliers.  I have included the Lagrange multipliers lambda and s as described in [Wikipedia article](https://en.wikipedia.org/wiki/Revised_simplex_method).

Relevant info from [#315](https://github.com/ERGO-Code/HiGHS/issues/315):
> There are always (virtual) slacks in HiGHS, whatever bounds the constraints have. HiGHS solves the LP with slacks s=Ax, (ie Ax-s=0) so that the slacks have the same bounds as the constraints. Thus the slacks are the "rows", and their values are in row_value.
>
> ... negated entries of row_dual are equivalent to lambda.  The sign difference comes from the fact that the slacks in HiGHS appear as Ax-s, rather than Ax+s

If you want to defer these to a later pull request, just ignore these return values for now (remove from OptimizeResult).

Please play around a little bit and verify that slack variables are being reported correctly (I just checked some simple examples).

I think the last thing to do is docs, how do you want to handle this?  Like I've mentioned, everything is written up in highs_wrapper docstring.

**Comment by mdhaber** [comment]
Very cool. I will probably wait on including Lagrange multipliers though. I will need to do quite a bit of testing for that. I'll try to get to the docs soon. In the meantime I will invite some reviewers.

**Comment by mckib2** [comment]
I've commented out Lagrange multipliers in `_linprog_highs.py`

**Review by mdhaber — APPROVED** [review]

**Pull request merged**
