### PR TITLE
Cython review response

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

https://github.com/scipy/scipy/pull/12043

#### What does this implement/fix?

- Removes many unneeded upstream files
- pulls upstream updates, most notably improvements to presolve  _EDIT: rolled back, waiting on upstream bug fixes_
- responses to @rgommers cython review
    - Adds LICENSE information
    - fixes to cython docstring
    - removes commented out code
    - code comment clarifications
    - prefer `encode()` to byte-strings

#### Additional information

Breaks 3 unit tests related to upgrades in presolve.  Currently I am skipping those tests to make everything else works while we wait for upstream fixes:
- test_zero_row_2
- test_singleton_row_ub_2
- test_cyclic_recovery

Probably not ready for merge until unit tests pass again.  _EDIT: rollback resolves unit test failures_

Upstream issue: https://github.com/ERGO-Code/HiGHS/issues/372

### CODE REVIEW

**Comment by mdhaber** [comment]
Can you undo the upstream updates so we can merge the responses to @rgommers comments?

**Comment by mckib2** [comment]
I can sure try, I've never tried to remove commits before.  Apologies, I thought since we were bumped to 1.6 that we'd have a little bit of time

**Comment by mdhaber** [comment]
Well, we do... but it might help keep reviewer attention.

**Comment by mckib2** [comment]
Reverted, removed unit test skips, should be ready to merge

**Comment by mdhaber** [comment]
Should I wait for CI?

**Comment by mckib2** [comment]
Yeah, let's wait to make sure.  I'd hate to fail for something stupid while everyone's looking ;)

**Comment by mckib2** [comment]
Looks good to go

**Pull request merged**
